// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCydFn471ZVW869lSekyQs3R3PUns2GqcE',
    appId: '1:684175359427:web:76a29924102987c78bd176',
    messagingSenderId: '684175359427',
    projectId: 'println-28e6d',
    authDomain: 'println-28e6d.firebaseapp.com',
    databaseURL: 'https://println-28e6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'println-28e6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0irAzBoSmM44NBZ4-SJEyuKrcYFHGGHw',
    appId: '1:684175359427:android:d05300c9d0e05b908bd176',
    messagingSenderId: '684175359427',
    projectId: 'println-28e6d',
    databaseURL: 'https://println-28e6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'println-28e6d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzCfufAxjxtyBOj4QbkcfXs6nJeZf5jBs',
    appId: '1:684175359427:web:51b67ad6c5cbcf4c8bd176',
    messagingSenderId: '684175359427',
    projectId: 'println-28e6d',
    authDomain: 'println-28e6d.firebaseapp.com',
    databaseURL: 'https://println-28e6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'println-28e6d.appspot.com',
  );
}
